title: Stephen A. Fuqua (safnet) - Blog
author: Stephen A. Fuqua
email: stephen@safnet.com
description: >
  Stephen A. Fuqua (SAF) is a Bahá'í, software engineer, and
  nature lover in Austin, Texas, USA.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.safnet.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: stephen_fuqua
github_username:  stephenfuqua

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


permalink: /archive/:year/:month/:day/:title/
paginate: 10
paginate_path: "page/:num"
category_dir: categories
